### ISSUE TITLE
Facebook login generates an infinite loop on iOS

### ISSUE THREAD

**Issue by fdobre** [colorfy-software/react-native-gigya-sdk#2] opened 2022-06-11 08:22 UTC
The bug is exactly as this one reported on stackoverflow here:

https://stackoverflow.com/questions/62186815/facebook-login-trapped-in-a-loop-if-open-in-facebook-app

Movie:
https://flair-inventory.s3-us-west-2.amazonaws.com/RPReplay_Final1591237513.MP4

It seems that when attempting to use the Gigya social login for iOS the library still wants to login the user even though it is already logged in. The bug seem to be related to current FB sdk dependencies.

Another similar bug reported here:
https://github.com/facebookarchive/react-native-fbsdk/issues/611

Is there any known workaround for this? Has any other user of the library reported this issue?

Any opinion or suggestion will be highly appreciated.

**Comment by CharlesMangwa** [comment] 2022-06-18 06:43
Hi @fdobre. It seems your issue is coming from a faulty implementation/configuration of the Facebook SDK on your side. Did you try [the solution](https://stackoverflow.com/a/47038186/4883700) mentioned in the react-native-fbsdk issue you mentioned? Also maybe make sure you properly set up your URL Schemes in your `Info.plist`.

That being said, this doesn't seem to be caused by this library at all, closing this issue therefore.

**Closed as completed by CharlesMangwa** 2022-06-18 06:43 UTC
Labels: invalid

**Comment by shivam-kakkar** [comment] 2022-08-02 16:29
For anyone facing this issue, I was stuck on this for 3 days and the only file that you need to check in case of infinite loop login is AppDelegate.m. I had issues because I was using multiple social auths and also deep linking.
Here's what fixed in my case. If you are using google login or any other social auths add an if condition for them too.

```
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options
{
  if ([[FBSDKApplicationDelegate sharedInstance] application:application openURL:url options:options]) {
    return YES;
  }

  if ([RNGoogleSignin application:application openURL:url options:options]) {
    return YES;
  }

  if ([RCTLinkingManager application:application openURL:url options:options]) {
    return YES;
  }

  return NO;
}
```
